name: LintProject

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    permissions:
      checks: write
      contents: write    
    uses: gentrop-cloud/actions_workflows/.github/workflows/lint.yaml@main
    with:
      node_version: '20'
